name: tests
on: push
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkput
        uses: actions/checkout@v2
      - name: setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Run tests with Maven
        run: |
          ls
          mvn -B test --file pom.xml
